import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import '@/styles/global.scss';
import ReactQueryProviders from '@/utils/ReactQueryProvider';
import {Provider} from 'jotai';
import PageTemplate from '@/components/template/PageTemplate';
import {Navbar, Sidebar} from '@/components/layout';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Provider>
					<ReactQueryProviders>
						<Navbar />
						<Sidebar />

						<PageTemplate>{children}</PageTemplate>
					</ReactQueryProviders>
				</Provider>
			</body>
		</html>
	);
}
